services:
  database:
    image: postgres
    restart: always
    
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - GIN_MODE=release
    depends_on:
      - database
    networks:
      - default
    ports:
    - "3579:3579"
volumes:
  data: